const CARVE_UP_ASSETS=['pentagon','moons','wall','oceans','letter'];

const REX_LOW_POINTS=[
 'You remember the night you lost the election. Your concession speech ran so long and loud that the translation bot quit mid-sentence and filed a formal complaint against you for a hostile work environment. Two bots quit.',
 'You demanded a recount of your own rally crowd because "the photos, they were way off, tiny numbers, fake news." The janitor who emptied the venue disputed your count publicly. The janitor says you lost to a tumbleweed.',
 'You corrected the official hurricane projection with a permanent marker, right on the live bureau screen, drawing a giant X over the whole galaxy. You blamed the marker. The marker is fine.',
 'On live television you opened your arms for a handshake. Nobody moved. You held the pose for a very long time, then announced, "They wanted it more than me, believe me."',
 'You descended the grand ceremonial ramp with a small child\u2019s water bottle in one hand, tripped on the carpet, and blamed the ramp, the carpet, and the "pod people who built it to embarrass me." The ramp never said a word.',
 'You signed an emergency decree in crayon that read "I AM A VERY STABLE GENUIS." The typo went on every commemorative mug in the galaxy. You still say it was intentional.',
 'You suggested, on live broadcast, they could "inject a little system cleaner, right into the lungs, very simple." The Galactic Medical Guild sent a strongly worded letter and a poster of a lung with an X on it.',
 'At a riot where one side carried little flags with your face and the other side carried a petition, you praised "very fine people on both sides." Both sides were confused. The petition is still unsigned.',
 'At the galaxy summit you huddled alone over a marker and a starchart of the moons while the other leaders literally turned their backs on you for the group photo. You mailed a copy of it back, edited, with yourself bigger.',
 'You said you knew "zero, nothing" about the ectoplasm dancer or any payment. Then a filing proved you knew everything. Then you called it "a perfectly legal allowance, for legal things." Nobody knows what that means.',
 'On the grand escalator you screamed at an aide, "WHERE\u2019S MY STARCHART? GET HER OUT," while the aide silently mouthed the words "he does this." It went viral. The aide got a raise.',
 'You told the assembled press "I won this election, tremendously, the most won." Then you turned and left while the teleprompter scrolled the actual results you hadn\u2019t read. The teleprompter has never respected you since.',
 'You bragged you would "win the Nebula Open, no contest, very athletic." The scorecard leaked, showing you played eleven rounds in nine days while a planetary crisis burned and your own advisors begged you to stop.',
 'You held a rally in an arena so empty the echo returned your own chant back to you before you finished it. You lost to the echo in a place you paid people to fill.',
];

const BUILDINGS=[
  {id:'fourmoons',name:'Four Moons Total Terraforming',upgradedName:'Four Moons Total Terraforming (The Scene of the Crime)',x:6,y:36,w:10,h:6,color:'#5a3a7a',icon:'\uD83C\uDF11',unlockPhase:0,door:{side:'bottom',gap:2},
   desc:'The venue Gargoyliani booked by mistake. Ectoplasm still stains the podium. This is where your lowest moment began.',
   actions:[
    {label:'Relive a Humiliating Memory',ap:0,cost:'free',eff:'Just memories. No mechanical effect.',
     flavor:'The Hits Keep Coming',
     ignoreDailyCap:true,
     apply:s=>{return pickMemory();}},
   ]},
  {id:'rally',name:'Rally Stage',upgradedName:'The Bigly Stage of Tremendous Success',x:25,y:8,w:8,h:6,color:'#a03030',icon:'\uD83C\uDFA0',unlockPhase:0,door:{side:'bottom',gap:2},
   desc:'A rickety stage made of stolen campaign funds and questionable plywood.',
   actions:[
    {label:'Hold MASSIVE Rally',ap:1,cost:'$8',eff:'+5-12 approval, +2-4 loyalty',
     flavor:'Crowd Size Will Be YUGE',
     apply:s=>{s.credits-=8;let a=ir(5,12);let l=ir(2,4);s.approval+=a;s.loyalty+=l;return 'The crowd goes wild! Some people are crying. One man is holding up a sign that says \u2018MY WIFE LEFT ME BUT BLOVIUS NEVER WILL.\u2019 This is healthy. Approval +'+a+'. Loyalty +'+l+'.'}},
    {label:'Incite the Mob',ap:1,cost:'2 fear',eff:'+3-8 fear, +2-5 approval',
     flavor:'Do Something Vague but Threatening',
     apply:s=>{let f=ir(3,8);let a=ir(2,5);s.fear-=2;s.fear+=f;s.approval+=a;return 'You point vaguely toward something and the crowd understands. Very smart people. The smartest. They\u2019ll figure out who to hate. They always do. Fear '+(f-2>=0?'+':'')+(f-2)+'. Approval +'+a+'.'}},
    {label:'Sell Red Caps',ap:0,cost:'free',eff:'+5-15 credits',
     flavor:'Made in Space-Sweatshops',
     apply:s=>{let g=ir(5,15);s.credits+=g;return 'Beautiful red caps flying off the shelves. +$'+g+'. The stitching is terrible but the branding is tremendous.'}},
   ]},
  {id:'courts',name:'The Courthouse',upgradedName:'The Hall of Totally Legal Decisions (Allegedly)',x:40,y:2,w:8,h:6,color:'#4040a0',icon:'\u2696',unlockPhase:0,door:{side:'bottom',gap:2},
   desc:'Where justice goes to die. Beautifully.',
   actions:[
    {label:'Pack Courts Like Sardines',ap:2,cost:'$12, 3 loyalty',eff:'Institutions -8-15',
     flavor:'More Corruption Per Square Inch',
     legalExposure:['election'],
     apply:s=>{s.credits-=12;s.loyalty-=3;let d=ir(8,15);s.institutions-=d;return 'Your people are in. Lifetime appointments. The most loyal judges. Incredibly loyal. They\u2019ll rule that water is dry if you ask nicely. Institutions: -'+d+'. Loyalty: -3. Costs $12.'}},
    {label:'Send Fruit Basket',ap:1,cost:'2 fear',eff:'Institutions -3-7, fear +2',
     flavor:'With a Severed Head Inside',
     apply:s=>{let d=ir(3,7);let f=ir(1,3);s.fear-=2;s.institutions-=d;s.fear+=f;return 'The judge knows what happens. Everyone knows. The fruit was\u2026 seasonal. Institutions: -'+d+'. Fear '+(f-2>=0?'+':'')+(f-2)+'.'}},
    {label:'File Frivolous Lawsuit #47',ap:1,cost:'$10',eff:'Institutions -2-5',
     flavor:'This One Will Work, Trust Me',
     apply:s=>{s.credits-=10;let d=ir(2,5);s.institutions-=d;return 'The legal system is slow. Very slow. But you just buried the courts in so much garbage that the real cases drown too. Institutions: -'+d+'. Costs $10. The judges stop taking it seriously. That\u2019s the point.'}},
    {label:'Contribute to Gargoyliani\u2019s Defense Fund',ap:0,cost:'$25',eff:'Settle his exposure \u2014 lowers his flip risk',
     flavor:'The Shysters Are Very Grateful',
     noGargoyleBill:true,
     ignoreDailyCap:true,
     costFn:()=>'$'+Math.min(GARGOYLIANI.settleCap,Math.max(0,Math.round(gargoyleBills))),
     apply:s=>{if(gargoyleBills<=0)return 'Gargoyliani has no pending bills. The lawyers are confused. And hungry.';let amt=Math.min(GARGOYLIANI.settleCap,Math.round(gargoyleBills));s.credits-=amt;gargoyleBills-=amt;if(gargoyleBills<0)gargoyleBills=0;updateGargoyle();if(gargoyleBills<=0)log('Gargoyliani\u2019s exposure cleared. He stops looking at the exits. For now.','good');return 'You pass $'+amt+' to Gargoyliani\u2019s defense fund. His exposure drops. He weeps with relief. Or ectoplasm. Hard to tell.'}},
    {label:'Pay Toward Your Outstanding Judgments',ap:((window.GAME_CONFIG&&window.GAME_CONFIG.LEGAL&&window.GAME_CONFIG.LEGAL.legalPayAtb!=null)?window.GAME_CONFIG.LEGAL.legalPayAtb:1),cost:'$50',eff:'Settle your own legal bills (costs 1 AP per visit, whatever the amount)',
     flavor:'The Awful Truth, Itemized',
     noGargoyleBill:true,
     ignoreDailyCap:true,
     disabledWhen:()=>totalLegalCost()<=0?'You owe nothing. Dragging your golden heels into court for zero reason would just waste a day.':null,
     costFn:()=>'$'+Math.min(LEGAL.settleCap,Math.max(0,Math.round(totalLegalCost()))),
     apply:s=>{let paid=payLegal(LEGAL.settleCap);if(paid<=0)return 'No judgments outstanding. The lawyers look disappointed. It\u2019s the most approved of you\u2019ve ever seen them look.';return 'You push $'+paid+' across the marble. A judgment is satisfied. Another stack of paper appears instantly, as if encouraged. Total still owed: $'+Math.round(totalLegalCost())+'.'}},
   ]},
  {id:'media',name:'Media Tower',upgradedName:'The Ministry of Alternative Facts',x:55,y:8,w:8,h:6,color:'#20808a',icon:'\uD83D\uDCFA',unlockPhase:0,door:{side:'bottom',gap:2},
   desc:'Where the truth goes to get a facelift.',
   actions:[
    {label:'Spread Beautiful Propaganda',ap:1,cost:'$6',eff:'+3-8 approval, +2-4 media, -2 institutions',
     flavor:'Now With 40% More Alternative Facts',
     apply:s=>{s.credits-=6;let a=ir(3,8);let m=ir(2,4);s.approval+=a;s.media+=m;s.institutions-=2;return 'Fake news? No. The MOST real news. Your news. Approval +'+a+'. Media +'+m+'. Institutions: -2. Costs $6.'}},
    {label:'Attack the Press',ap:1,cost:'1 fear',eff:'Media +3-7, Institutions -3-5',
     flavor:'They Started It',
     legalExposure:['suppression'],
     apply:s=>{let m=ir(3,7);let i=ir(3,5);s.fear-=1;s.media+=m;s.institutions-=i;return 'The lying press shrinks. Media control: +'+m+'. Institutions: -'+i+'. Fear: -1. They should\u2019ve thought about that before reporting truth.'}},
    {label:'Demand Retraction',ap:0,cost:'$4',eff:'+1-4 approval, media +1',
     flavor:'Or We\u2019ll Cry on Live TV',
     apply:s=>{s.credits-=4;let a=ir(1,4);s.approval+=a;s.media+=1;return 'They print what you want. For now. You made a very compelling face on camera. The sad one. It worked. Approval +'+a+'. Media +1. Costs $4.'}},
   ]},
  {id:'business',name:'Business District',upgradedName:'The Grift Exchange & Casino',x:25,y:25,w:10,h:8,color:'#a0a020',icon:'\uD83D\uDCB0',unlockPhase:0,door:{side:'bottom',gap:2},
   desc:'Where capitalism meets creativity meets crime.',
   actions:[
    {label:'The Most Beautiful Grift',ap:1,cost:'free',eff:'+12-35 credits, -2-5 approval',
     flavor:'It\u2019s Not Stealing If You\u2019re Famous',
     legalExposure:['swindling'],
     apply:s=>{let g=ir(12,35);let a=ir(2,5);s.credits+=g;s.approval-=a;return 'Money. Beautiful money. +$'+g+'. Approval: -'+a+'. It\u2019s not corruption if you\u2019re having fun. And you\u2019re having a BLAST.'}},
    {label:'Bribe Officials',ap:1,cost:'$15',eff:'+4-8 loyalty, institutions -3',
     flavor:'Everyone Has a Price, Yours Is Pathetic',
     legalExposure:['swindling','election'],
     apply:s=>{let l=ir(4,8);s.credits-=15;s.loyalty+=l;s.institutions-=3;return 'Everyone has a price. Yours was surprisingly low. Loyalty +'+l+'. Institutions: -3. Costs $15. They pretend to think about it first, for dignity\u2019s sake. But we all know.'}},
    {label:'Extort Businesses',ap:1,cost:'2 fear',eff:'+8-22 credits, -2 approval',
     flavor:'Capitalism With Extra Steps',
     legalExposure:['swindling'],
     apply:s=>{let g=ir(8,22);s.fear-=2;s.credits+=g;s.approval-=2;return 'Protection. Very important. They pay because they want to. +$'+g+'. Fear: -2. Approval: -2. It\u2019s just capitalism with extra steps. Very entrepreneurial.'}},
   ]},
  {id:'military',name:'Military Base',upgradedName:'Fort Definitely-Not-Compensating-For-Something',x:55,y:25,w:8,h:8,color:'#20a020',icon:'\u2694',unlockPhase:1,door:{side:'bottom',gap:2},
   desc:'Big trucks. Big guns. Tiny hands. Coincidence?',
    actions:[
     {label:'Recruit "Volunteers"',ap:0,cost:'$6',eff:'+1-2 military',
      flavor:'Nobody Ever Leaves. Ever.',
      apply:s=>{s.credits-=6;let g=ir(1,2);s.military+=g;return 'You hold a recruitment drive. The \u2018volunteers\u2019 are given a form, a uniform, and absolutely no choice in the matter. A family of four signs up because the alternative involved a very pointed stare. Military: +'+g+'. Costs $6.'}},
     {label:'Rally the Troops',ap:1,cost:'$10',eff:'+4-8 military, +2-4 loyalty',
     flavor:'They\u2019ll Do Whatever You Say, It\u2019s Terrifying',
     apply:s=>{let m=ir(4,8);let l=ir(2,4);s.credits-=10;s.military+=m;s.loyalty+=l;return 'The troops love you. The most patriotic troops. They salute. Beautiful. They\u2019ll do whatever you say. That\u2019s\u2026 actually terrifying. Military +'+m+'. Loyalty +'+l+'. Costs $10.'}},
    {label:'Intimidate Opponents',ap:1,cost:'2 military',eff:'+4-8 fear, -2 approval',
     flavor:'Show Them Your Tank Collection',
     legalExposure:['suppression'],
     apply:s=>{let f=ir(4,8);s.military-=2;s.fear+=f;s.approval-=2;return 'Tanks in the streets. Very stable. Very reassuring. One of them has your name painted on it. Fear +'+f+'. Approval: -2. Military: -2.'}},
    {label:'Declare Emergency',ap:2,cost:'4 military',eff:'Institutions -8-15, fear +8-15',
     flavor:'Again. This Is the 47th One This Week.',
     legalExposure:['suppression'],
     apply:s=>{let i=ir(8,15);let f=ir(8,15);s.military-=4;s.institutions-=i;s.fear+=f;return 'EMERGENCY DECLARED. The most emergency emergency ever. Institutions: -'+i+'. Fear +'+f+'. Military: -4. This is the 47th one this week. But who\u2019s counting?'}},
   ]},
  {id:'border',name:'The Great Wall',upgradedName:'The Great Big Beautiful Wall of Tremendous Proportions (Andromeda\u2019s Tab)',x:40,y:40,w:12,h:4,color:'#8a7a30',icon:'\uD83E\uDDF1',unlockPhase:2,door:{side:'bottom',gap:3},
   desc:'It\u2019s big, it\u2019s beautiful, and Andromeda is definitely paying for it. Probably.',
   actions:[
     {label:'Deport Dissidents',ap:2,cost:'3 fear, 2 military',eff:'Population -5-12, fear +5-10',
      flavor:'To Where? Don\u2019t Worry About It',
      legalExposure:['deportation'],
      apply:s=>{let p=ir(5,12);let f=ir(5,10);s.fear-=3;s.military-=2;s.population-=p;s.fear+=f;return 'The ships leave. Beautiful ships. They don\u2019t come back. Nobody asks where they go. Population: -'+p+'. Fear '+(f-3>=0?'+':'')+(f-3)+'. Military: -2. And you\u2019re sure there will be no economic consequences. Right?'}},
     {label:'Seal the Border',ap:1,cost:'$8, 2 military',eff:'Population -3-8, institutions +3',
      flavor:'Nobody Gets In or Out. Especially Out.',
      legalExposure:['deportation'],
      apply:s=>{let p=ir(3,8);s.credits-=8;s.military-=2;s.population-=p;s.institutions+=3;return 'Nobody gets in. Nobody gets out. The most sealed border. Beautiful. Population: -'+p+'. Institutions +3. Military: -2. Costs $8. Especially the \u2018out\u2019 part.'}},
    {label:'Build Wall Higher',ap:1,cost:'$12',eff:'Institutions +3-6, approval +2-4',
     flavor:'The Galaxy\u2019s Biggest Wall. The Andromedans Will Pay.',
     apply:s=>{let i=ir(3,6);let a=ir(2,4);s.credits-=12;s.institutions+=i;s.approval+=a;return 'YUGE wall. The most beautiful wall. Ten feet higher. Institutions: +'+i+'. Approval +'+a+'. Costs $12. It looks incredible. The Andromedans are definitely paying for it.'}},
   ]},
  {id:'palace',name:'Blovius Tower',upgradedName:'Blovius Tower of Power (and Also Some Apartments)',x:38,y:15,w:10,h:8,color:'#a06020',icon:'\uD83C\uDFF0',unlockPhase:0,door:{side:'bottom',gap:2},
   desc:'Your seat of power. The penthouse has golden toilets. Obviously.',
   actions:[
    {label:'Host Gala',ap:2,cost:'$20',eff:'+6-12 loyalty, +3-5 approval',
     flavor:'Caviar, Champagne, and Casual Treason',
     apply:s=>{let l=ir(6,12);let a=ir(3,5);s.credits-=20;s.loyalty+=l;s.approval+=a;return 'The most beautiful gala. Everyone is there. The best people. The caviar is from a endangered species but it\u2019s delicious. Loyalty +'+l+'. Approval +'+a+'. Costs $20.'}},
    {label:'Sign Executive Order',ap:1,cost:'free',eff:'Random: +/-5-12 on any stat',
     flavor:'Using a Crayon, Like a Real Leader',
     apply:s=>{let stats=['approval','fear','loyalty','military','institutions','media'];let t=pick(stats);let d=ir(-12,12);s[t]=clampVal(s[t]+d,0,100);return 'SIGNED. In crayon. Like a REAL leader. '+t.toUpperCase()+' changed by '+(d>0?'+':'')+d+'. Executive power is INCREDIBLE.'}},
    {label:'Watch Yourself on TV',ap:0,cost:'free',eff:'+1-3 approval',
     flavor:'Your Favorite Activity',
      apply:s=>{let d=ir(1,3);s.approval+=d;return 'You look incredible on TV. The most photogenic leader. The hair. The chin. The overall mass. Approval +'+d+'.'}},
    ]},
  {id:'firesale',name:'The Fire Sale Emporium',upgradedName:'The Fire Sale Emporium of Tremendous Bargains (Everything Must Go)',x:6,y:8,w:8,h:6,color:'#7a2a7a',icon:'\uD83D\uDEAB',unlockPhase:3,door:{side:'bottom',gap:2},
   desc:'The galaxy is a fire sale and everything must go. Sell your friends the parts of it you no longer need. One sale per asset: once it\u2019s gone, it\u2019s gone.',
   actions:[
    {label:'Sell the Pentagon to Space-Space X',ap:0,cost:'free',eff:'+120 credits, -a few soldiers (they\u2019re part of the deal)',
     flavor:'The X stands for \u2018even more space!\u2019',
     once:true,asset:'pentagon',
     apply:s=>{s.credits+=120;s.military-=2;return 'SPACE\u2013SPACE X! Get it? Space\u2019s already in the name, so we doubled it. Absolutely not a shell company. They buy the Pentagon, the tanks, and, unbeknownst to them, the troops still inside. +$120. Military: -2. The soldiers ship with the building. TERMS AND CONDITIONS.'}},
    {label:'Sell the Four Moons to an LLC',ap:0,cost:'free',eff:'+90 credits',
     flavor:'Name TBD. Probably Not Moon LLC.',
     once:true,asset:'moons',
      apply:s=>{s.credits+=90;return 'You sell the Four Moons to \u2018Inevitable Property Group, LLC.\u2019 The tides haven\u2019t worked right since your last Blovius Tower was built \u2014 but that\u2019s their problem now. +$90.'}},
    {label:'Sell the Great Wall to Andromeda (She\u2019s Paying After All)',ap:0,cost:'free',eff:'+70 credits',
     flavor:'See? I Knew It.',
     once:true,asset:'wall',
     apply:s=>{s.credits+=70;return 'Andromeda finally pays for the wall. The whole wall. Every last stone. +$70. She insists she \u2018always intended to.\u2019 Sure, Andromeda. Sure. The wall is now her problem. And her teeth are still lovely.'}},
    {label:'Sell the Oceans to Blovius-Corp',ap:0,cost:'free',eff:'+70 credits',
     flavor:'Sustainability Is for Losers.',
     once:true,asset:'oceans',
     apply:s=>{s.credits+=70;return 'Your own corporation buys the oceans. What\u2019s a little vertical integration? +$70. The fish are confused. The water is \u2018pre-sold futures.\u2019 You are the ocean now. Emotionally.'}},
    {label:'Auction the People\u2019s Commemorative Letter from \u2018Little Rocket Man\u2019',ap:0,cost:'free',eff:'+50 credits',
     flavor:'The Archives cite the Presidential Records Act. Same folk who swore the Hatchet Act mattered.',
     once:true,asset:'letter',
      apply:s=>{s.credits+=50;return 'It\u2019s not your letter \u2014 it belongs to the people. Specifically, to a museum. Where it technically belongs to everyone. So you sell it to your friend. +$50. The people will love that the crown jewel of their \u2018cultural heritage\u2019 now hangs in a billionaire\u2019s bathroom. Beautiful. This is what they voted for.'}},
    ]},
  {id:'bureau',name:'The Bureau of Tremendous Science',upgradedName:'The Bureau of Tremendous Science & Public Charm',x:56,y:46,w:8,h:6,color:'#3a88b0',icon:'\uD83C\uDFDB',unlockPhase:1,door:{side:'bottom',gap:2},
   desc:'A gleaming complex where the science is whatever you decree, and the public is charmed whether they like it or not.',
   actions:[
    {label:'Publish a Peer-(Bribe)viewed Study',ap:1,cost:'$8',eff:'+2-4 media, +1-3 approval, -1-2 institutions',
     flavor:'The Charts Are Illegal but Convincing',
     legalExposure:['suppression'],
     apply:s=>{let m=ir(2,4);let a=ir(1,3);let i=ir(1,2);s.credits-=8;s.media+=m;s.approval+=a;s.institutions-=i;return 'A \u2018rigorous, independent\u2019 study drops. It wraps your rule in lab coats and footnotes. Media +'+m+'. Approval +'+a+'. The institutions that might fact-check are now too busy reading it. Institutions: -'+i+'.'}},
    {label:'Run a \u2018Public Health\u2019 Survey',ap:1,cost:'2 military',eff:'-2-4 population, +2-4 fear',
     flavor:'They\u2019re Going to a Better Place. The Place Is Unclear.',
     legalExposure:['deportation'],
     apply:s=>{let p=ir(2,4);let f=ir(2,4);s.military-=2;s.population-=p;s.fear+=f;return 'The survey identifies \u2018non-compliant biology.\u2019 The volunteers are relocated. For their health. Population: -'+p+'. Fear +'+f+'. The medical journals are confused. Nobody asks the volunteers. They\u2019re resting comfortably. Allegedly.'}},
    {label:'Sell \u2018Official\u2019 Health Certificates',ap:0,cost:'free',eff:'+6-12 credits, -1-2 approval',
     flavor:'Stamp of Legitimacy. Sold Separately.',
     legalExposure:['swindling'],
     apply:s=>{let c=ir(6,12);let a=ir(1,2);s.credits+=c;s.approval-=a;return 'For a small \u2018processing fee,\u2019 anyone can be officially healthy. +$'+c+'. Approval: -'+a+'. The stamps are beautiful. The registry is a napkin. The napkin is yours.'}},
   ]},
];

const NPC_TYPES=[
  {type:'supporter',name:'MAGA Citizen',color:'#c03030',icon:'\uD83E\uDEE1',iconFallback:'M',
   greet:['YOU\u2019RE THE GREATEST!','I named my firstborn after you! He\u2019s 45 and very confused!','Four moons! FOUR MOONS!','Most tremendous leader!','We love you, Rex! My wife left me because I love you more!'],
    quickLabel:'Wave to a Crowd',
    quickEff:s=>{let v=ir(1,2);s.loyalty+=v;return 'You wave to a friendly crowd. Loyalty +'+v+'. The face on the flag is slightly off-center. It\u2019s the thought that counts.'},
    fullCost:1,fullEff:'Rile Up (1AP) (+4-8 loyalty, +2-5 fear)',
   fullApply:s=>{let l=ir(4,8);let f=ir(2,5);s.loyalty+=l;s.fear+=f;return 'You rile them up. They would die for you. Most loyal people. One is actually crying. Loyalty +'+l+'. Fear +'+f+'. This is healthy behavior.'}},
  {type:'citizen',name:'Ordinary Citizen',color:'#606060',icon:'\uD83D\uDC64',
   greet:['I just want to live my life, pay my taxes, and pretend this isn\u2019t happening.','Please...','What did we do?','Is that too much to ask? Apparently yes.','I have children...'],
   quickLabel:'Glare Tactfully',
    quickEff:s=>{s.fear+=1;return pick(['They flinch as you pass. Fear +1. It\u2019s working.','Fear +1. They know. They\u2019ve learned.','They cross the street. Fear +1. Smart.'])},
   fullCost:1,fullEff:'Threaten (1AP) (+2-4 fear, -1 approval)',
   legalExposure:['suppression'],
   fullApply:s=>{let f=ir(2,4);s.fear+=f;s.approval-=1;return 'They look terrified. One of them is updating their will. Another is googling \u2018how to flee to another dimension.\u2019 Fear +'+f+'. Approval: -1. The fear is spreading. Tremendous.'}},
  {type:'protester',name:'Protester',color:'#3090c0',icon:'\uD83D\uDCE3',
   greet:['DEMOCRACY NOW! Or at least a functional government!','Rex is a fraud!','WE WILL NOT COMPLY!','Or literally anything better than this sentient toupee!'],
   quickLabel:'Shout Back Briefly',
    quickEff:s=>{s.fear+=1;s.approval-=1;return 'You trade a few shouted lines. Fear +1. Approval: -1.'},
   fullCost:1,fullEff:'Argue With Them (1AP)',
   fullApply:s=>{if(Math.random()<0.5){let a=ir(1,3);let f=ir(0,2);s.approval+=a;s.fear+=f;return 'You shout back. Some of them actually listen. A few wander off. Approval +'+a+'. Fear +'+f+'. The rest shout louder. But hey, some progress.';}else{let f=ir(1,3);let a=ir(1,2);s.fear+=f;s.approval-=a;return 'You shout back. It goes poorly. Fear +'+f+'. Approval: -'+a+'. They\u2019re louder now. The interpretative dance has added a new movement called \u2018The Fascist Shuffle.\u2019 It\u2019s going viral.';}}},
  {type:'reporter',name:'Reporter',color:'#c0c030',icon:'\uD83C\uDFA4',
   greet:['Rex, a comment? Preferably one that doesn\u2019t get me arrested this time?','Sources say...','Is this legal?','The public deserves truth.'],
   quickLabel:'Pose for a Photo',
    quickEff:s=>{s.media+=1;return 'Camera flashes. Media +1. You look incredible. The flash catches your best angle.'},
    cost:'$8',
    fullCost:1,fullEff:'Bribe (1AP) (+3-6 approval, media +1-3)',
    fullApply:s=>{let a=ir(3,6);let m=ir(1,3);s.credits-=8;s.approval+=a;s.media+=m;return '\u2018REX: A MISUNDERSTOOD GENIUS\u2019 \u2014 front page. Approval +'+a+'. Media +'+m+'. Costs $8. The most beautiful headline. They\u2019ll print anything for $8.'}},
  {type:'judge',name:'Judge',color:'#8080d0',icon:'\u2696',
   greet:['The law is the law, Mr. Rex.','Even when it\u2019s... *sigh*... let me check my retirement fund first.','You cannot be above it.','This ends.'],
    quickLabel:'Test the Waters',
     quickEff:s=>{let r=Math.random();if(r<0.5){let a=ir(1,2);s.approval+=a;return 'You test the waters. The judge lets a ruling slide your way. Their pen hovers. Then moves past the part where it would\u2019ve hurt you. Approval +'+a+'.';}else if(r<0.8){return pick(['They glare. Very judgmental. They say nothing. Nothing is fine.','They adjust their glasses disapprovingly. Then look away. Good enough.','They shuffle papers in a way that means \u2018we\u2019re watching you.\u2019 Noted.']);}else{let i=1;s.institutions+=i;return 'The system pushes back. A quiet ruling moves the other way. Institutions +'+i+'. The system resists. Sad.';}},
    cost:'$8',
    fullCost:1,fullEff:'Pressure (1AP) (Institutions -4-8)',
    fullApply:s=>{s.credits-=8;let d=ir(4,8);s.institutions-=d;return 'The judge cracks. They all crack. Institutions: -'+d+'. Costs $8. Easy. They really should\u2019ve taken that retirement offer.'}},
  {type:'oligarch',name:'Oligarch',color:'#c0a020',icon:'\uD83D\uDCB0',
   greet:['I smell profit. And also burning democracy. But mostly profit.','What are the terms?','My yacht, your policy.','Business is business.'],
    quickLabel:'Take a Modest Gift',
    quickEff:s=>{let v=ir(3,8);s.credits+=v;return pick(['They hand you cash. +$'+v+'. The best people.','A briefcase appears. It\u2019s heavy. And warm. +$'+v+'. Don\u2019t ask.'])},
   fullCost:1,fullEff:'Deal (1AP) (+10-25 credits, +2-4 loyalty)',
    fullApply:s=>{let g=ir(10,25);let l=ir(2,4);s.credits+=g;s.loyalty+=l;return 'Beautiful deal. +$'+g+'. Loyalty +'+l+'. The oligarchs love you. The best deal makers. Democracy was overrated anyway.'}},
  {type:'general',name:'Military General',color:'#30c030',icon:'\uD83C\uDF96',
    greet:['Ready for orders, sir. Please don\u2019t make me violate the Genova Nebula Convention. Again.','The troops await.','Loyalty is everything.','For you, always.'],
    quickLabel:'Accept a Salute',
    quickEff:s=>{let v=ir(0,1);s.military+=v;if(v===0)return pick(['A salute. Beautiful. Nothing to add.','They snap to attention. One of them is sweating.']);return 'Military +'+v+'. '+pick(['They are ready.','A salute. Beautiful.','They snap to attention. One of them is sweating.']);},
   fullCost:1,fullEff:'Demand Loyalty Oath (1AP) (+3-6 loyalty, +2-4 military)',
   fullApply:s=>{let l=ir(3,6);let m=ir(2,4);s.loyalty+=l;s.military+=m;return 'The loyalty oath. The most beautiful oath. Loyalty +'+l+'. Military +'+m+'. They salute you. Incredible. The Genova Nebula Convention is merely a suggestion at this point.'}},
  {type:'goon',name:'Your Goon',color:'#802020',icon:'\uD83E\uDD4A',
   greet:['Who\u2019s needs whackin\u2019? My baseball bat is lonely and my alibi is solid.','Say the word.','Ready.','Consider it done.'],
    quickLabel:'Give a Nod',
    quickEff:s=>{let v=ir(0,1);s.fear+=v;if(v===0)return pick(['They crack their knuckles. Intimidating. Nothing changes.','They sharpen something. You don\u2019t ask what.']);return 'Fear +'+v+'. '+pick(['Problems solve themselves.','They crack their knuckles. Intimidating.','They sharpen something. You don\u2019t ask what.']);},
   fullCost:1,fullEff:'Silence Someone (1AP) (+3-6 fear, +1-2 loyalty, -1-3 approval)',
   legalExposure:['murder'],
    fullApply:s=>{let f=ir(3,6);let l=ir(1,2);let a=ir(1,3);s.fear+=f;s.loyalty+=l;s.approval-=a;return 'Problem solved. Permanently. Fear +'+f+'. Loyalty +'+l+'. Approval: -'+a+'. The most permanent solution. They don\u2019t make problems like they used to. Because they\u2019re gone now.'}},
  {type:'scientist',name:'Quack Scientist',color:'#6030a0',icon:'\uD83D\uDD2C',weight:2,
   greet:['My research is peer-reviewed by whoever I can bribe.','I can prove anything. Give me funding and enough ectoplasm.','The damp towels? A control group.','I have a theory, and it\u2019s very convenient.'],
    quickLabel:'Mumble to a Camera',
     quickEff:s=>{let v=ir(1,2);s.media+=v;return 'You have the quack mumble vague \u2018findings\u2019 to a camera crew. A few people nod. Media +'+v+'. It\u2019s noise, but it\u2019s confident noise.'},
    cost:'$8',
    fullCost:1,fullEff:'Authorize a Questionable Study (1AP) (+2-4 media, -2-4 institutions)',
    legalExposure:['suppression'],
    fullApply:s=>{let m=ir(2,4);let i=ir(2,4);s.credits-=8;s.media+=m;s.institutions-=i;return 'A \u2018comprehensive study\u2019 is published. Totally independent. It wraps your rule in lab coats. Media +'+m+'. The courts are distracted. Institutions: -'+i+'. The methodology is ectoplasm. It\u2019s a masterpiece.'}},
  {type:'real_scientist',name:'Real Scientist',color:'#3a88b0',icon:'\uD83D\uDC68\u200D\uD83D\uDD2C',weight:2,
   greet:['My results are reproducible. I verified them, Mr. Rex.','The data don\u2019t lie. I do, if I\u2019m honest. Today I choose not to.','You can\u2019t suppress a peer-reviewed finding by shouting. Oh gods \u2014 you\u2019re doing it right now, aren\u2019t you?','I have a methodology. It is not for sale at any price. Certain prices, maybe.','My lab coat is the only clean thing in this city.'],
    quickLabel:'Suppress Data',
    quickEff:s=>{let m=ir(1,2);let i=-1;s.media+=m;s.institutions+=i;return 'You stand behind the scientist while they retract a single embarrassing slide. The press barely notices. Media +'+m+'. The institution that might cite it loses a little credibility. Institutions: '+i+'.'},
   // Full actions (1 quick + 2 full). Bribe and Menace both cost AP.
   fullActions:[
    {label:'Bribe the Scientist',ap:1,cost:'$12',eff:'+3-6 media, -2-5 institutions',
     legalExposure:['swindling'],
     apply:s=>{let m=ir(3,6);let i=ir(2,5);s.credits-=12;s.media+=m;s.institutions-=i;return 'You slide a stack of credits across the lab bench. The scientist hesitates. Then pockets enough for a new grant and buries the inconvenient data. Media +'+m+'. The study \u2018wasn\u2019t statistically significant.\u2019 Institutions: -'+i+'. Costs $12. Science, but make it profitable.'}},
    {label:'Menace the Scientist',ap:1,cost:'2 fear',eff:'+3-6 media, +2-4 fear, -1-3 approval',
     legalExposure:['suppression'],
     apply:s=>{let m=ir(3,6);let f=ir(2,4);let a=ir(1,3);s.fear-=2;s.media+=m;s.fear+=f;s.approval-=a;return 'You lean in very close and explain the funding situation. The scientist understands. The retraction is drafted by lunch. Media +'+m+'. Fear '+(f-2>=0?'+':'')+(f-2)+'. Approval: -'+a+'. The methodology is intact. The nerve is not.'}},
   ]},
  {type:'spy',name:'Spy Asset',color:'#2a6a5a',icon:'\uD83D\uDD75',weight:2,
   greet:['I can get you anything. Secrets, dirt, a slightly suspicious bank account.','The walls have ears. I have better ones.','What\u2019s your figure? I have a figure for you.','Partner, I know things.'],
   quickLabel:'Take the Temperature',
   quickEff:s=>{let v=ir(1,2);s.fear+=v;return 'The asset adjusts their sunglasses meaningfully. The shadows get a little colder. Fear +'+v+'. They know where the bodies are. So does everyone who sees them.'},
   fullCost:1,fullEff:'Trade Secrets (1AP) (+8-18 credits, -2-3 loyalty, -2-4 institutions)',
   legalExposure:['election'],
   fullApply:s=>{let c=ir(8,18);let l=ir(2,3);let i=ir(2,4);s.credits+=c;s.loyalty-=l;s.institutions-=i;return 'The asset sells you someone else\u2019s secrets. +$'+c+'. Your inner circle is nervous. Loyalty: -'+l+'. The institutions that might notice are quietly broken. Institutions: -'+i+'. Cash is cash.'}},
  {type:'influencer',name:'Influencer',color:'#c03a8a',icon:'\uD83D\uDCF1',weight:2,
   greet:['The algorithm loves you. I checked. It\u2019s weird but it loves you.','I can make anyone hate who you hate. And love who you are.','Genuine question: what\u2019s your brand? No, don\u2019t answer. I can fix it.','The engagement is through the moon. Literally. Four of them.'],
   quickLabel:'Boost a Clip',
    quickEff:s=>{let v=ir(1,3);s.media+=v;return 'The influencer boosts a clip of you looking \u2018extremely presidential.\u2019 It\u2019s all light and no truth. Media +'+v+'.'},
    fullCost:1,fullEff:'Amplify the Narrative (1AP) (+4-7 media, +3-6 approval)',
    fullApply:s=>{let m=ir(4,7);let a=ir(3,6);s.media+=m;s.approval+=a;return 'A coordinated surge. Every feed glows with your best angle. Media +'+m+'. Approval +'+a+'. The narrative holds. The truth is somewhere else, probably with the damp towels.'}},
  {type:'unionboss',name:'Union Boss',color:'#b06020',icon:'\u270A',weight:2,
   greet:['My members vote how I tell \u2019em. Ask around.','You want workers? I want silence. Deal?','They strike, I blink. Tell me your numbers.','Labor and order, hand in hand. Sweaty hand.'],
   quickLabel:'Take a Cut',
   quickEff:s=>{let v=ir(2,6);s.credits+=v;return 'The boss palms you a cut. \u2018Union dues.\u2019 +$'+v+'. Nobody asks what the workers get. They\u2019re busy. Working.'},
   fullCost:1,fullEff:'Crush the Strike (1AP) (+4-7 fear, -1-3 population, -2-3 approval)',
   legalExposure:['suppression'],
   fullApply:s=>{let f=ir(4,7);let p=ir(1,3);let a=ir(2,3);s.fear+=f;s.population-=p;s.approval-=a;return 'The strike is \u2018resolved.\u2019 The picket lines are empty. Fear +'+f+'. Population: -'+p+'. Approval: -'+a+'. The workers return to work, smiling, because they know what\u2019s good for them. The boss nods. Business as usual.'}},
];
